name: RedstoneCommand
main: com.bukkit.HomerBond005.RedstoneCommand.RedstoneCommand
version: 2.6.7
author: HomerBond005
description: >
             RedstoneCommand
commands:
    rsc:
        description: Toggles redstone power.
        usage: Type /<command> for help.