name: RedstoneCommand
main: de.HomerBond005.RedstoneCommand.RedstoneCommand
version: 3.0.3
author: HomerBond005
description: Toggle redstone via a command.
commands:
    rsc:
        description: Toggles redstone power and provides other functions.
        usage: Type /<command> for help.