name: RedstoneCommand
main: de.homerbond005.redstonecommand.RedstoneCommand
version: '@PROJECT_VERSION@'
author: HomerBond005
description: Toggle redstone via a command.
commands:
    rsc:
        description: Toggles redstone power and provides other functions.
        usage: Type /<command> for help.