name: RedstoneCommand
main: de.HomerBond005.RedstoneCommand.RedstoneCommand
version: 2.7
author: HomerBond005
description: >
             RedstoneCommand
commands:
    rsc:
        description: Toggles redstone power.
        usage: Type /<command> for help.